name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Python dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file for testing
      working-directory: ./backend
      run: |
        echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}" > .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
    
    - name: Test backend configuration
      working-directory: ./backend
      run: |
        python -c "import os; from dotenv import load_dotenv; load_dotenv(); print('✅ Backend environment loaded successfully')"
    
    - name: Install Frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
    
    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm run build
    
    - name: Success notification
      run: |
        echo "✅ All checks passed!"
        echo "✅ Backend configured"
        echo "✅ Frontend built successfully"
